### PR TITLE
Increase php upload limit to 50M

### PR DESCRIPTION
**Pull request by jackinloadup**
cuz 2M isn't enough

### CODE REVIEW

**Comment by smfsh** [comment]
I feel this change should be made in the PHP container in the php.ini file located there. The .htaccess file in web is provided by Drupal as a stock default and I don't think this is where these settings should go.

**Comment by jackinloadup** [comment]
@smfsh how about now?

**Comment by jackinloadup** [comment]
Requires running `make docker-rebuild` to test I believe.

**Comment by smfsh** [comment]
I think the M notation in ini files is for the weak. This should be converted to bytes like God intended.

**Pull request merged**
